M48
; DRILL file {KiCad (6.0.5-0)} date Friday, 05 August 2022 at 10:19:10
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-05T10:19:10+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X3.5197Y-4.0394
X3.5197Y-4.1181
T2
X3.4646Y-3.4646
X4.4094Y-4.4094
T0
M30
